### ISSUE TITLE
Regex support

### ISSUE THREAD

**Issue by jarodium** [itgalaxy/generate-robotstxt#130]
Hello,

I'm picking up this list of user agents at https://github.com/monperrus/crawler-user-agents/.

They have an entry containing "patterns" that could resolve into or more entries.
Does this library supports or could support such regexes?

For example

` "pattern": "[wW]get",`

yields these entries in robots.xt

wget
Wget

Thanks

**Comment by alexander-akait** [comment]
No regexp support, it is very hard to implement converting regexps to all possible strings, sorry
