### ISSUE TITLE
Check limit of length rule `Clean-param`

### ISSUE THREAD

**Issue by drabodan** [itgalaxy/generate-robotstxt#2]
It takes as long Yandex permit rules are not more than 500 characters.
https://yandex.ru/support/webmaster/controlling-robot/robots-txt.xml?lang=ru#clean-param

**Comment by evilebottnawi** [comment]
Done in https://github.com/itgalaxy/generate-robotstxt/commit/5ae4bb076d4e880e28944045e412d202972652e9
