### ISSUE TITLE
'Disallow:' directive ignored on falsy property

### ISSUE THREAD

**Issue by jsamr** [itgalaxy/generate-robotstxt#92]
The following configuration:

``` json
{
    "userAgent": "*",
    "disallow":  ""
}
```
ends up in the following robots.txt :
```
User-agent: *
```
instead of
```
User-agent: *
Disallow:
```

**Comment by evilebottnawi** [comment]
@jsamr Thanks for issue, today i will fix

**Comment by jsamr** [comment]
@evilebottnawi thank you !

**Comment by evilebottnawi** [comment]
@jsamr hm, according spec https://developers.google.com/search/reference/robots_txt, `Disallow` can not be empty

**Comment by jsamr** [comment]
@evilebottnawi Interesting, the [robots-txt manual first example](http://robots-txt.com/) has such directive:

```
User-agent: *
Disallow:
```

And [this specification](http://www.robotstxt.org/orig.html#format) states:

```
Disallow
    (...)

    Any empty value, indicates that all URLs can be retrieved.
    At least one Disallow field needs to be present in a record.
```

**Comment by evilebottnawi** [comment]
@jsamr looks google spec and official spec are difference :confused: :laughing:

**Comment by evilebottnawi** [comment]
Let's support official version

**Comment by jsamr** [comment]
@evilebottnawi awesome, thanks :-)

**Comment by evilebottnawi** [comment]
Done in https://github.com/itgalaxy/generate-robotstxt/releases/tag/5.0.5
